---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-telemetry
resources:
  - namespace.yaml
  - service-account.yaml
  - component-frontend.yaml
  # - component-frontend-proxy.yaml